if(NOT DEFINED BOOKSIM2_DOWNLOAD_URL OR BOOKSIM2_DOWNLOAD_URL STREQUAL "")
    message(FATAL_ERROR "BOOKSIM2_DOWNLOAD_URL is not set.")
endif()

if(NOT DEFINED BOOKSIM2_EXECUTABLE OR BOOKSIM2_EXECUTABLE STREQUAL "")
    message(FATAL_ERROR "BOOKSIM2_EXECUTABLE is not set.")
endif()

get_filename_component(BOOKSIM2_TARGET_DIR "${BOOKSIM2_EXECUTABLE}" DIRECTORY)
file(MAKE_DIRECTORY "${BOOKSIM2_TARGET_DIR}")

message(STATUS "Downloading BookSim executable from ${BOOKSIM2_DOWNLOAD_URL}")
file(
    DOWNLOAD
    "${BOOKSIM2_DOWNLOAD_URL}"
    "${BOOKSIM2_EXECUTABLE}"
    STATUS DOWNLOAD_STATUS
    SHOW_PROGRESS
    TLS_VERIFY ON
)

list(GET DOWNLOAD_STATUS 0 DOWNLOAD_STATUS_CODE)
list(GET DOWNLOAD_STATUS 1 DOWNLOAD_STATUS_MESSAGE)
if(NOT DOWNLOAD_STATUS_CODE EQUAL 0)
    file(REMOVE "${BOOKSIM2_EXECUTABLE}")
    message(FATAL_ERROR "Failed to download booksim.exe: ${DOWNLOAD_STATUS_MESSAGE}")
endif()

message(STATUS "booksim.exe downloaded to ${BOOKSIM2_EXECUTABLE}")
